### ISSUE TITLE
`sno switch` fails with error

### ISSUE THREAD

**Issue by hamishcampbell** [koordinates/sno#257]
Sno version:

```
Sno v0.5.1.dev0+ci.937.gitf5d2afd1, Copyright (c) Sno Contributors
» GDAL v3.0.3; PROJ v6.3.0
» PyGit2 v1.1.0; Libgit2 v0.99.0; Git v2.27.0
» APSW v3.32.2-r1; SQLite v3.32.1; SpatiaLite v4.3.0a; Libpq v12.0.3
» SpatialIndex v1.9.3
```

Calling `sno switch` with no arguments produces the following output:

```
$  sno switch
Traceback (most recent call last):
  File "sno_cli.py", line 4, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "sno/cli.py", line 129, in invoke
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 21, in new_func
  File "sno/checkout.py", line 187, in switch
  File "pygit2/repository.py", line 1202, in __getitem__
TypeError: argument 1 must be str, not None
[10065] Failed to execute script sno_cli
```

I expected this to give a suitable 'help' message, for example how `sno import` works:

```
$ sno import
Usage: sno import [OPTIONS] SOURCE [TABLES]...
Try 'sno import --help' for help.

Error: Missing argument 'SOURCE'.
```

**Comment by olsen232** [comment]
Fixed at https://github.com/koordinates/sno/commit/d189781c
