### ISSUE TITLE
`updrade-to-tidy` failing

### ISSUE THREAD

**Issue by hamishcampbell** [koordinates/sno#286]
MacOS Sno built from master https://github.com/koordinates/sno/commit/4c8eb2198d1e94bb3d0d26156e8eb71210412cab

```
Sno v0.5.1.dev0, Copyright (c) Sno Contributors
» GDAL v3.0.3; PROJ v6.3.0
» PyGit2 v1.1.0; Libgit2 v0.99.0; Git v2.27.0
» APSW v3.32.2-r1; SQLite v3.32.1; SpatiaLite v4.3.0a; Libpq v12.0.3
» SpatialIndex v1.9.3
```

I attempted to run `sno upgrade-to-tidy` in an old repository with a GPKG working copy, it failed like so:

```
$ sno upgrade-to-tidy .
Traceback (most recent call last):
  File "/usr/local/bin/sno", line 33, in <module>
    sys.exit(load_entry_point('sno', 'console_scripts', 'sno')())
  File "/Users/hamish/code/kx/sno/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/hamish/code/kx/sno/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/hamish/code/kx/sno/sno/cli.py", line 131, in invoke
    return super().invoke(ctx)
  File "/Users/hamish/code/kx/sno/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/hamish/code/kx/sno/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/hamish/code/kx/sno/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/hamish/code/kx/sno/sno/upgrade/__init__.py", line 248, in upgrade_to_tidy
    tidy_repo.write_config(repo_version, wc_path, is_bare)
  File "/Users/hamish/code/kx/sno/sno/sno_repo.py", line 196, in write_config
    WorkingCopy.write_config(self, wc_path, bare)
  File "/Users/hamish/code/kx/sno/sno/working_copy/base.py", line 125, in write_config
    elif cls.is_postgres_uri(path):
  File "/Users/hamish/code/kx/sno/sno/working_copy/base.py", line 98, in is_postgres_uri
    return path.startswith("postgresql:")
AttributeError: 'PosixPath' object has no attribute 'startswith'

If you suspect this is an IPython 7.18.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

It left the repo in a broken state - the new `.sno` folder exists but sno isn't recognizing it from them the working copy folder.

**Comment by olsen232** [comment]
You can fix this particular repo by running the following from within the repo:
`printf "gitdir: .sno\n" > .git`
In the meantime, I'll fix the bug

**Comment by olsen232** [comment]
Fixed at https://github.com/koordinates/sno/commit/11a95e7
