### ISSUE TITLE
Executing `sno commit` in a non sno repo directory crashes

### ISSUE THREAD

**Issue by UberMouse** [koordinates/sno#31]
```
Traceback (most recent call last):
  File "/usr/local/bin/sno", line 11, in <module>
    load_entry_point('sno==0.2.1.dev0', 'console_scripts', 'sno')()
  File "/usr/local/Cellar/sno/HEAD-4f861e4/libexec/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/sno/HEAD-4f861e4/libexec/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/sno/HEAD-4f861e4/libexec/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/sno/HEAD-4f861e4/libexec/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/sno/HEAD-4f861e4/libexec/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/sno/HEAD-4f861e4/libexec/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/sno/HEAD-4f861e4/libexec/lib/python3.7/site-packages/sno/commit.py", line 50, in commit
    repo = pygit2.Repository(repo_dir)
  File "/usr/local/Cellar/sno/HEAD-4f861e4/libexec/lib/python3.7/site-packages/pygit2/repository.py", line 1270, in __init__
    path_backend = init_file_backend(path)
_pygit2.GitError: Repository not found at .
```

**Comment by rcoup** [comment]
AFAICT this was fixed in #35
