### ISSUE TITLE
sno help lists wrong help text for `gc` command

### ISSUE THREAD

**Issue by hamishcampbell** [koordinates/sno#351]
```
Sno v0.7.2.dev0+ci.1452.git96f701fe, Copyright (c) Sno Contributors
» GDAL v3.2.0; PROJ v6.3.0
» PyGit2 v1.3.0; Libgit2 v1.1.0; Git v2.29.2
» APSW v3.33.0-r1; SQLite v3.33.0; SpatiaLite v5.0.0; Libpq v13.0.1
» SpatialIndex v1.9.3
```

---

The output for `sno help` includes the incorrect help text for `gc`:

```
gc                  Get and set repository or global options
```

As does the output of `sno help gc`

```
Usage: sno help [OPTIONS] [ARGS]...

  Get and set repository or global options

Options:
  --help  Show this message and exit.
```

I expected this to display accurate help text for the garbage collect operation.

Note also that supplying `help` with an invalid option results in an unhandled error:

```
$ sno help doesnotexist
Traceback (most recent call last):
  File "sno_cli.py", line 4, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "sno/cli.py", line 131, in invoke
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 21, in new_func
  File "sno/cli_util.py", line 15, in help
KeyError: 'f'
[9402] Failed to execute script sno_cli
```

**Comment by olsen232** [comment]
Fixed at e284c96
